services:
  db:
    image: postgres:16-alpine
    container_name: adms_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: adms_api
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d adms_api"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adms_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: Asia/Jakarta
      APP_NAME: "ADMS API"
      DATABASE_URL: "postgresql://postgres:postgres_password@db:5432/adms_api?schema=public"
      JWT_SECRET: "adms-default-super-secret-key"
      JWT_EXPIRES: 3600
      JWT_REFRESH_SECRET: "adms-default-super-secret-refresh-key"
      JWT_REFRESH_EXPIRES: 31536000
      AUTHOR_NAME: "Sejator Dev"
      AUTHOR_EMAIL: "sejatordev@gmail.com"
      WEBHOOK_TIMEOUT_MS: 30000
      WEBHOOK_CONCURRENCY: 1
      WEBHOOK_URL_REWRITE_FROM: "https://stg-pjlp.palembang.go.id"
      WEBHOOK_URL_REWRITE_TO: "http://pjlp-be:5003"
    networks:
      - default
      - pjlp-net
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  pjlp-net:
    external: true
    name: sistem-opd_pjlp-net
